package com.etoak.bean;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;


public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.ID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String id;
    
    
    private List<BookPic> pics=new ArrayList<BookPic>();
    
    public List<BookPic> getPics() {
		return pics;
	}
    public void setPics(List<BookPic> pics) {
		this.pics = pics;
	}
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.NAME
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.PRICE
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date publishdate;
    
    private String dateStr;
    public String getDateStr() {
    	SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
    	return format.format(this.publishdate);
	}
    
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.STATUS
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String categoryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOK.TOTAL
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private BigDecimal total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.ID
     *
     * @return the value of SCOTT.BOOK.ID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.ID
     *
     * @param id the value for SCOTT.BOOK.ID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.NAME
     *
     * @return the value of SCOTT.BOOK.NAME
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.NAME
     *
     * @param name the value for SCOTT.BOOK.NAME
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.PRICE
     *
     * @return the value of SCOTT.BOOK.PRICE
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.PRICE
     *
     * @param price the value for SCOTT.BOOK.PRICE
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.AUTHOR
     *
     * @return the value of SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.AUTHOR
     *
     * @param author the value for SCOTT.BOOK.AUTHOR
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @return the value of SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public Date getPublishdate() {
        return publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.PUBLISHDATE
     *
     * @param publishdate the value for SCOTT.BOOK.PUBLISHDATE
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setPublishdate(Date publishdate) {
        this.publishdate = publishdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.STATUS
     *
     * @return the value of SCOTT.BOOK.STATUS
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.STATUS
     *
     * @param status the value for SCOTT.BOOK.STATUS
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.CATEGORYID
     *
     * @return the value of SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.CATEGORYID
     *
     * @param categoryid the value for SCOTT.BOOK.CATEGORYID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setCategoryid(String categoryid) {
        this.categoryid = categoryid == null ? null : categoryid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOK.TOTAL
     *
     * @return the value of SCOTT.BOOK.TOTAL
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public BigDecimal getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOK.TOTAL
     *
     * @param total the value for SCOTT.BOOK.TOTAL
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    
    private   Category  category;
    
	public void setCategory(Category category) {
		this.category = category;
	}
	public Category getCategory() {
		return category;
	}
}