package com.etoak.dao;

import com.etoak.bean.BookPic;
import com.etoak.bean.BookPicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int countByExample(BookPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int deleteByExample(BookPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int insert(BookPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int insertSelective(BookPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    List<BookPic> selectByExample(BookPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    BookPic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") BookPic record, @Param("example") BookPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByExample(@Param("record") BookPic record, @Param("example") BookPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByPrimaryKeySelective(BookPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOKPIC
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByPrimaryKey(BookPic record);
}