package com.etoak.dao;

import com.etoak.bean.Category;
import com.etoak.bean.CategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int countByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int deleteByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    List<Category> selectByExample(CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    Category selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByExample(@Param("record") Category record, @Param("example") CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.CATEGORY
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByPrimaryKey(Category record);
}