package com.etoak.dao;

import com.etoak.bean.Book;
import com.etoak.bean.BookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int countByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int deleteByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int insertSelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    List<Book> selectByExample(BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    Book selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByPrimaryKeySelective(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.BOOK
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    int updateByPrimaryKey(Book record);
}