package com.etoak.bean;

public class BookPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOKPIC.ID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOKPIC.SAVEPATH
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String savepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOKPIC.SHOWNAME
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String showname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOKPIC.FM
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String fm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.BOOKPIC.BOOKID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    private String bookid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOKPIC.ID
     *
     * @return the value of SCOTT.BOOKPIC.ID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOKPIC.ID
     *
     * @param id the value for SCOTT.BOOKPIC.ID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOKPIC.SAVEPATH
     *
     * @return the value of SCOTT.BOOKPIC.SAVEPATH
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getSavepath() {
        return savepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOKPIC.SAVEPATH
     *
     * @param savepath the value for SCOTT.BOOKPIC.SAVEPATH
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setSavepath(String savepath) {
        this.savepath = savepath == null ? null : savepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOKPIC.SHOWNAME
     *
     * @return the value of SCOTT.BOOKPIC.SHOWNAME
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getShowname() {
        return showname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOKPIC.SHOWNAME
     *
     * @param showname the value for SCOTT.BOOKPIC.SHOWNAME
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setShowname(String showname) {
        this.showname = showname == null ? null : showname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOKPIC.FM
     *
     * @return the value of SCOTT.BOOKPIC.FM
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getFm() {
        return fm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOKPIC.FM
     *
     * @param fm the value for SCOTT.BOOKPIC.FM
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setFm(String fm) {
        this.fm = fm == null ? null : fm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.BOOKPIC.BOOKID
     *
     * @return the value of SCOTT.BOOKPIC.BOOKID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public String getBookid() {
        return bookid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.BOOKPIC.BOOKID
     *
     * @param bookid the value for SCOTT.BOOKPIC.BOOKID
     *
     * @mbggenerated Tue Nov 21 20:14:57 CST 2017
     */
    public void setBookid(String bookid) {
        this.bookid = bookid == null ? null : bookid.trim();
    }
}